// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {filesystem} from '../models';

export function GitLookup():Promise<boolean>;

export function OpenFileByDialog():Promise<filesystem.FileDetails>;

export function ReadDirTree(arg1:string):Promise<filesystem.DirTree>;

export function ReadFileContent(arg1:string):Promise<filesystem.FileContentResult>;
