// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GitLookup() {
  return window['go']['core']['App']['GitLookup']();
}

export function ModifyFileContent(arg1, arg2) {
  return window['go']['core']['App']['ModifyFileContent'](arg1, arg2);
}

export function OpenFileByDialog() {
  return window['go']['core']['App']['OpenFileByDialog']();
}

export function OpenFolderByDialog() {
  return window['go']['core']['App']['OpenFolderByDialog']();
}

export function ReadDirTree(arg1) {
  return window['go']['core']['App']['ReadDirTree'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['core']['App']['ReadFileContent'](arg1);
}
